sonar.projectKey=federico1809_insight-commerce-recsys
sonar.organization=datulito
sonar.projectName=insight-commerce-recsys
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc,data/**,models/**,notebooks/**,reports/**
sonar.sourceEncoding=UTF-8